### ISSUE TITLE
Script save error: Error: @match: Could not parse the pattern: https://term.ptt.cc

### ISSUE THREAD

**Issue by Cycatz** [VdustR/term-ptt-custom-theme#1]
I found I can't save the script with `@match https://term.ptt.cc` in Greasemonkey.
![image](https://user-images.githubusercontent.com/24320926/194817765-c3592f90-2f4a-4d0f-846e-4d9ff56872be.png)

But it works when changed to `@match *://term.ptt.cc/*`. 

Did I do something wrong or the script requires specific Greasemonkey version?

**Comment by VdustR** [comment]
I found that the trailing slash is required for GreaseMonkey. I tried `https://term.ptt.cc/` and it works. I'll updated the document. Thanks for feedback~
